name: platform_screener
description: A Flutter utility to detect platform and screen orientation (Android, iOS, Web, macOS, Linux, Windows, PWA, etc.) for responsive UI design.
version: 0.0.3

homepage: https://github.com/Shanu33
repository: https://github.com/Shanu33/platform_screener
issue_tracker: https://github.com/Shanu33/platform_screener/issues

environment:
  sdk: ">=3.7.0 <4.0.0"

linter:
  rules:
    public_member_api_docs: true

dependencies:
  flutter:
    sdk: flutter
  adaptive_linear_layout: ^0.0.5
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/google_icon.svg
    - assets/Images/Flower_half.jpg
    - assets/Images/hiFi.gif
