name: platform_screener
description: >
  A Flutter utility for responsive UI design that detects the device platform
  (Android, iOS, Web, Windows, Linux, macOS, PWA Mobile/Desktop,
  or even desktop-site-on-mobile) and screen orientation (portrait or landscape)
  to help customize layouts gracefully on every screen and platform.
version: 0.0.1

homepage: https://github.com/Shanu33
repository: https://github.com/Shanu33/platform_screener
issue_tracker: https://github.com/Shanu33/platform_screener/issues

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_linear_layout: ^0.0.5
  flutter_svg: ^2.0.9
  figma_squircle: ^0.6.3
  js: ^0.6.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/google_icon.svg
    - assets/Images/Flower_half.jpg
    - assets/Images/hiFi.gif
